#env:
#  global:
#  - secure: LLkxKuTpD5D4k8x8qCXKGdwLpQvlVZ0AuC0TOYTPcZfm0VJE/Ppg+XgikiIdlD5f2+u/fBfn6FwMfdcnawGrNCJjNtLuQ9Dp4vTvqBfgsUhmkPAkV1nbKajYSgyAvFxKyhYhQlLra3gV6pplIFtKg7KZmtwnN5BqWmvA4m3rd9U=
#  - secure: bpXQdUjLAAF+IQLgsZPGA8Dy5YgbJvRW4QO0zEzLmFTl7/Cr5OsKHFEWtBoGlziP+l+A+iDLTDYsX6gF6d9WFv1SItnMEWwNzWG7ef4sQ4VSoK9vdJ9bon/a+mU3Za1rZ1hd9PjJBuhj6QY4pmIQiMebcuYP0ekg6zsn3RNSO1Q=
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# install local gitlab
before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential zlib1g-dev libyaml-dev libssl-dev libgdbm-dev libreadline-dev libncurses5-dev libffi-dev curl openssh-server redis-server checkinstall libxml2-dev libxslt-dev libcurl4-openssl-dev libicu-dev logrotate python-docutils pkg-config cmake
  - sudo apt-get install -y git-core
  - git --version
  - sudo apt-get remove -y ruby1.8
  - mkdir /tmp/ruby && pushd /tmp/ruby
  - curl -L --progress ftp://ftp.ruby-lang.org/pub/ruby/2.1/ruby-2.1.2.tar.gz | tar xz
  - cd ruby-2.1.2
  - ./configure --disable-install-rdoc
  - make
  - sudo make install
  - sudo gem install bundler --no-ri --no-rdoc
  - sudo apt-get install -y mysql-server mysql-client libmysqlclient-dev
  - mysql --version
  - popd
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: coverage run --source=gitlab setup.py test
after_success:
  coveralls