env:
  - gitlab_user=root gitlab_password=5iveL!fe gitlab_host=http://localhost:8080
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
rvm:
  - 2.1.0
# install local gitlab
before_install:
  - scripts/install_gitlab_omnibus.sh
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: coverage run --source=gitlab setup.py test
after_success:
  coveralls