env:
  - gitlab_user=root gitlab_password=5iveL!fe gitlab_host=http://localhost:8080
services:
  - redis-server
  - postgresql
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
cache: bundler
# install local gitlab
before_install:
  - sudo apt-get install -y build-essential zlib1g-dev libyaml-dev libssl-dev libgdbm-dev libreadline-dev libncurses5-dev libffi-dev curl checkinstall libxml2-dev libxslt-dev libcurl4-openssl-dev libicu-dev logrotate python-docutils pkg-config cmake git-core
  - psql -c 'create database git;' -U postgres
  - psql -c 'CREATE DATABASE gitlabhq_production OWNER git;' -U postgres
  - scripts/prepare_test_env.sh
  - scripts/install_gitlab.sh
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: coverage run --source=gitlab setup.py test
after_success:
  coveralls